name: Static Project Deployment Pipeline
description: Deploys a static project to RPRs S3 bucket.
inputs:
  AWS_ACCESS_KEY_ID:
    description: The AWS access key ID.
    required: false
    default: AKIASERYN65TMTVK3K5J
  AWS_SECRET_ACCESS_KEY:
    description: The AWS secret access key.
    required: false
    default: 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
  AWS_REGION:
    description: The target AWS region.
    required: false
    # default: us-east-1
    default: us-west-1
  AWS_S3_BUCKET:
    description: The target S3 bucket to sync with.
    required: false
    # default: rpr.to
    default: rprs3test
  AWS_S3_ENDPOINT:
    description: The AWS endpoint.
    required: false
    default: s3.amazonaws.com
  SOURCE_DIR:
    description: The local directory (or file) you wish to sync/upload to S3.
    required: false
    default: public
  DEST_DIR:
    description: The directory inside of the S3 bucket you wish to sync/upload to.
    required: true

runs:
  using: composite
  steps:
  - name: Checkout Branch
    uses: actions/checkout@master

  - run: echo KEY ${{ AWS_ACCESS_KEY_ID }}.
    shell: bash
  - run: echo inputs ${{ inputs.DEST_DIR }}.
    shell: bash
  - run: echo DEST ${{ DEST_DIR }}.
    shell: bash

  # - name: Deploy to S3
  #   uses: SeligLabs/gitactions@s3-deploy
  #   with:
  #     args: --acl public-read --follow-symlinks --delete
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
  #     AWS_REGION: ${{ inputs.AWS_REGION }}
  #     AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
  #     SOURCE_DIR: ${{ inputs.SOURCE_DIR }}
  #     DEST_DIR: ${{ inputs.DEST_DIR }}
