name: Static Project Deployment Pipeline
description: Deploys a static project to RPRs S3 bucket.
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: composite
  steps:
  - name: Checkout Branch
    uses: actions/checkout@master

  - run: echo Hello ${{ inputs.who-to-greet }}.
    shell: bash

  # - name: Deploy to S3
  #   uses: SeligLabs/gitactions@s3-deploy
  #   with:
  #     args: --acl public-read --follow-symlinks --delete
  #   env:
  #     AWS_ACCESS_KEY_ID: AKIASERYN65TMTVK3K5J
  #     AWS_SECRET_ACCESS_KEY: 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
  #     # AWS_REGION: 'us-west-1'
  #     AWS_S3_BUCKET: rprs3test
  #     # AWS_S3_BUCKET: rpr.to
  #     SOURCE_DIR: 'public'      # optional: defaults to entire repository
