name: Project Name
description: Gets the correct project name to be used based upon branch and project configurations.
author: Selig Labs, Inc <info@seliglabs.com>
inputs:
  branch:
    description: The branch the triggered the Git Action.
    required: true
outputs:
  prefix:
    description: The project name.
    value: ${{ steps.prefix.outputs.value }}
runs:
  using: composite
  steps:
    - name: Get Prefix
      id: prefix
      shell: bash
      run: |
        case ${{ inputs.branch }} in
          dev | development)
            ::set-output name=value::Development
            ;;

          qa)
            ::set-output name=value::QA
            ;;

          internal)
            ::set-output name=value::Internal
            ;;

          stage | staging)
            ::set-output name=value::Staging
            ;;

          *)
            ::set-output name=value::""
            ;;
        esac
